### PR TITLE
Add usage example based on PW's debug state to readme

### PR DESCRIPTION
**Pull request by marcus-herrmann**
This was my first thought when I learned of Blick (kudos, btw!).

### CODE REVIEW

**Comment by owzim** [comment]
Thanks, shouldn't versioning be **active** when debug is **inactive**?, so:

``` php
$config->blick = array(
    'jsVersioning' => !$config->debug,
    'cssVersioning' => !$config->debug,
    'imgVersioning' => !$config->debug
);
```

**Comment by owzim** [comment]
The same could be applied for referencing the `min` files:

``` php
$config->blick = array(
    'jsVersioning' => !$config->debug,
    'cssVersioning' => !$config->debug,
    'imgVersioning' => !$config->debug,
    'jsMin' => !$config->debug,
    'cssMin' => !$config->debug,
    'imgMin' => !$config->debug,
);
```

If you could add that too, I'd be happy to pull.

**Comment by marcus-herrmann** [comment]
Don't you intend to cache bust via versioning? That was my idea behind it.

**Comment by owzim** [comment]
Developing local, with tools like Chrome dev tools, you can prevent caching out of the box. I use versioning rather for the live site, so that the visitor is not served an old file after updates. Oder?

**Comment by marcus-herrmann** [comment]
_I_ do as well, but it happens that I show a projects progress to a customer and want to make sure that I neednt have to rely on my customers ability to clear cache ;)

**Comment by owzim** [comment]
Yeah, that's why I would not bind it to `debug` in the stage of developing and showing revisions, later on that binding makes sense to me.

**Comment by marcus-herrmann** [comment]
I see.

**Pull request closed without merging**
